server:
  port: 8086
  servlet:
    context-path: /payment
spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://root:viet12345@localhost:27017/payment-service?authSource=admin
app:
  services:
    order: http://localhost:8084

