server:
  port: 8083
  servlet:
    context-path: /product
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:viet12345@localhost:27017/product-service?authSource=admin
app:
  services:
    inventory: http://localhost:8085