server:
  port: 8081
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service
  datasource:
    url: "jdbc:mysql://localhost:3307/vorder_cart_service?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: viet12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  services:
    product: http://localhost:8083